In [2]:
import torch

In [3]:
import numpy as np

## Creating a tensor

In [4]:
data = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
tensor1 = torch.tensor(data)

In [6]:
type(tensor1)

torch.Tensor

In [7]:
tensor1

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
tensor1.shape

torch.Size([3, 3])

## Creating tensor from numpy array

In [9]:
numpy1 = np.array([[1,2,3],[4,5,6]])

In [10]:
type(numpy1)

numpy.ndarray

In [11]:
numpy1

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
numpy1.shape

(2, 3)

In [13]:
tensor2 = torch.tensor(numpy1)

In [14]:
type(tensor2)

torch.Tensor

In [15]:
tensor2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
tensor2.shape

torch.Size([2, 3])

## Another way to create a tensor from a numpy array is to use torch.from_numpy()

In [17]:
tensor3 = torch.from_numpy(numpy1)

In [18]:
type(tensor3)

torch.Tensor

In [19]:
tensor3.shape

torch.Size([2, 3])

## Creating tensor from another tensor - by default the tensor will retain the properties of the original tensor unless explicitly changed

#### Retain the original values

In [20]:
x_ones = torch.ones_like(tensor3)

In [21]:
x_ones

tensor([[1, 1, 1],
        [1, 1, 1]])

In [22]:
x_ones.shape

torch.Size([2, 3])

#### Change the attributes of the original tensor

In [23]:
x_rands = torch.rand_like(tensor3, dtype = torch.float32)

In [24]:
x_rands

tensor([[0.1841, 0.8435, 0.7147],
        [0.2334, 0.8330, 0.7844]])

## Preparing the tensors with predefined shape

In [25]:
shape = (3,4)

In [26]:
tensor_one = torch.ones(shape)

In [27]:
tensor_one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
tensor_one.shape

torch.Size([3, 4])

In [29]:
tensor_zeroes = torch.ones(shape)

In [30]:
tensor_zeroes

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
tensor_zeroes.shape

torch.Size([3, 4])

In [32]:
tensor_rand = torch.rand(shape)

In [33]:
tensor_rand

tensor([[0.0330, 0.4961, 0.9372, 0.4448],
        [0.9274, 0.4274, 0.6832, 0.4961],
        [0.6619, 0.1870, 0.1047, 0.4231]])

In [34]:
tensor_rand.shape

torch.Size([3, 4])

## Attributes of a tensor

In [35]:
tensor = torch.rand(3,4)

In [36]:
tensor.shape

torch.Size([3, 4])

In [37]:
tensor.dtype

torch.float32

In [38]:
tensor.device

device(type='cpu')

## Moving tensors to accelerator

In [39]:
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
    # print(tensor_on_gpu)
    print(tensor.device)
else:
    print("GPU not avialble, running on {tensor.device}")

mps:0


## Tensor Operations

In [40]:
tensor = torch.rand([3,4])

In [41]:
tensor.shape

torch.Size([3, 4])

In [42]:
tensor

tensor([[0.7618, 0.7583, 0.0899, 0.5737],
        [0.1075, 0.2219, 0.3549, 0.3771],
        [0.9392, 0.4049, 0.4057, 0.5823]])

In [43]:
tensor[0] # First row

tensor([0.7618, 0.7583, 0.0899, 0.5737])

In [44]:
tensor[:,0] # all rows, first column

tensor([0.7618, 0.1075, 0.9392])

In [45]:
tensor[:,-1] # all rows last column

tensor([0.5737, 0.3771, 0.5823])

In [46]:
tensor[:,1] = 0 # all rows, 1 st column set to 0 

In [47]:
tensor

tensor([[0.7618, 0.0000, 0.0899, 0.5737],
        [0.1075, 0.0000, 0.3549, 0.3771],
        [0.9392, 0.0000, 0.4057, 0.5823]])

## Joining tensors

In [48]:
tensor

tensor([[0.7618, 0.0000, 0.0899, 0.5737],
        [0.1075, 0.0000, 0.3549, 0.3771],
        [0.9392, 0.0000, 0.4057, 0.5823]])

In [49]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1) # dimenstion = 1 means add as columns

In [50]:
t1

tensor([[0.7618, 0.0000, 0.0899, 0.5737, 0.7618, 0.0000, 0.0899, 0.5737, 0.7618,
         0.0000, 0.0899, 0.5737],
        [0.1075, 0.0000, 0.3549, 0.3771, 0.1075, 0.0000, 0.3549, 0.3771, 0.1075,
         0.0000, 0.3549, 0.3771],
        [0.9392, 0.0000, 0.4057, 0.5823, 0.9392, 0.0000, 0.4057, 0.5823, 0.9392,
         0.0000, 0.4057, 0.5823]])

In [51]:
t2 = torch.cat([tensor, tensor, tensor], dim = 0) # dimenstion = 0 means add as rows

In [52]:
t2

tensor([[0.7618, 0.0000, 0.0899, 0.5737],
        [0.1075, 0.0000, 0.3549, 0.3771],
        [0.9392, 0.0000, 0.4057, 0.5823],
        [0.7618, 0.0000, 0.0899, 0.5737],
        [0.1075, 0.0000, 0.3549, 0.3771],
        [0.9392, 0.0000, 0.4057, 0.5823],
        [0.7618, 0.0000, 0.0899, 0.5737],
        [0.1075, 0.0000, 0.3549, 0.3771],
        [0.9392, 0.0000, 0.4057, 0.5823]])

## Arithmetic Operations

In [53]:
tensor

tensor([[0.7618, 0.0000, 0.0899, 0.5737],
        [0.1075, 0.0000, 0.3549, 0.3771],
        [0.9392, 0.0000, 0.4057, 0.5823]])

In [54]:
tensor.shape

torch.Size([3, 4])

In [55]:
tensor.T

tensor([[0.7618, 0.1075, 0.9392],
        [0.0000, 0.0000, 0.0000],
        [0.0899, 0.3549, 0.4057],
        [0.5737, 0.3771, 0.5823]])

In [56]:
t1 = tensor

In [57]:
t2 = tensor.T

In [58]:
t2.shape

torch.Size([4, 3])

In [59]:
t1.shape

torch.Size([3, 4])

In [60]:
y1 = t1 @ t2

In [61]:
y1

tensor([[0.9177, 0.3302, 1.0861],
        [0.3302, 0.2797, 0.4645],
        [1.0861, 0.4645, 1.3857]])

In [62]:
y2 = t1.matmul(t2)

In [63]:
y2

tensor([[0.9177, 0.3302, 1.0861],
        [0.3302, 0.2797, 0.4645],
        [1.0861, 0.4645, 1.3857]])

## Elementwise multiplication

In [64]:
t1

tensor([[0.7618, 0.0000, 0.0899, 0.5737],
        [0.1075, 0.0000, 0.3549, 0.3771],
        [0.9392, 0.0000, 0.4057, 0.5823]])

In [65]:
t2

tensor([[0.7618, 0.1075, 0.9392],
        [0.0000, 0.0000, 0.0000],
        [0.0899, 0.3549, 0.4057],
        [0.5737, 0.3771, 0.5823]])

In [66]:
t1 * t1

tensor([[0.5804, 0.0000, 0.0081, 0.3292],
        [0.0116, 0.0000, 0.1259, 0.1422],
        [0.8820, 0.0000, 0.1646, 0.3391]])

In [67]:
t1.mul(t1)

tensor([[0.5804, 0.0000, 0.0081, 0.3292],
        [0.0116, 0.0000, 0.1259, 0.1422],
        [0.8820, 0.0000, 0.1646, 0.3391]])

## Single Element tensors

In [68]:
tensor

tensor([[0.7618, 0.0000, 0.0899, 0.5737],
        [0.1075, 0.0000, 0.3549, 0.3771],
        [0.9392, 0.0000, 0.4057, 0.5823]])

In [69]:
tensor.sum()

tensor(4.1922)

In [70]:
agg = tensor.sum()

In [71]:
agg

tensor(4.1922)

In [72]:
agg = tensor.sum(dim = 0)

In [73]:
agg

tensor([1.8085, 0.0000, 0.8505, 1.5332])

In [74]:
agg = tensor.sum(dim = 1)

In [75]:
agg

tensor([1.4255, 0.8395, 1.9271])

In [76]:
agg = tensor.sum()

In [77]:
agg

tensor(4.1922)

In [78]:
type(agg)

torch.Tensor

In [79]:
agg_item = agg.item()

In [80]:
agg_item

4.192152976989746

In [81]:
type(agg_item)

float

## Inplace operations

In [82]:
tensor

tensor([[0.7618, 0.0000, 0.0899, 0.5737],
        [0.1075, 0.0000, 0.3549, 0.3771],
        [0.9392, 0.0000, 0.4057, 0.5823]])

In [83]:
tensor.add_(5) # have underscore means it will change the original tensor, without underscore it will create a new tensor with the added value

tensor([[5.7618, 5.0000, 5.0899, 5.5737],
        [5.1075, 5.0000, 5.3549, 5.3771],
        [5.9392, 5.0000, 5.4057, 5.5823]])

In [84]:
tensor

tensor([[5.7618, 5.0000, 5.0899, 5.5737],
        [5.1075, 5.0000, 5.3549, 5.3771],
        [5.9392, 5.0000, 5.4057, 5.5823]])

## Tensor to numpy array

In [85]:
t = torch.ones(5)

In [86]:
t

tensor([1., 1., 1., 1., 1.])

In [87]:
n = t.numpy()

In [88]:
type(n)

numpy.ndarray

In [89]:
n

array([1., 1., 1., 1., 1.], dtype=float32)

#### Any change in tensor will change the numpy also because they share the memory

In [90]:
t.add_(5)

tensor([6., 6., 6., 6., 6.])

In [91]:
t

tensor([6., 6., 6., 6., 6.])

In [92]:
n

array([6., 6., 6., 6., 6.], dtype=float32)

## Numpy to tensor array

In [93]:
n = np.ones(5)

In [94]:
n

array([1., 1., 1., 1., 1.])

In [95]:
t = torch.from_numpy(n)

In [96]:
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [97]:
np.add(n,10, out = n)

array([11., 11., 11., 11., 11.])

In [98]:
n

array([11., 11., 11., 11., 11.])

In [99]:
t

tensor([11., 11., 11., 11., 11.], dtype=torch.float64)

## View in tensor 

In [100]:
tensor

tensor([[5.7618, 5.0000, 5.0899, 5.5737],
        [5.1075, 5.0000, 5.3549, 5.3771],
        [5.9392, 5.0000, 5.4057, 5.5823]])

In [104]:
tensor.shape

torch.Size([3, 4])

#### tensor - view is similar to reshape in numpy

In [105]:
tensor.view(2,6)

tensor([[5.7618, 5.0000, 5.0899, 5.5737, 5.1075, 5.0000],
        [5.3549, 5.3771, 5.9392, 5.0000, 5.4057, 5.5823]])

In [106]:
tensor

tensor([[5.7618, 5.0000, 5.0899, 5.5737],
        [5.1075, 5.0000, 5.3549, 5.3771],
        [5.9392, 5.0000, 5.4057, 5.5823]])

## Tensor - squeeze
#### squueze will only remove the dimensions of size 1. 
#### If we specifically describe the dimention, then only if the dimension is 1 then it will be squuezed else not

In [116]:
shape = (1,3,1,5)

In [117]:
t1 = torch.rand(shape)

In [118]:
t1.shape

torch.Size([1, 3, 1, 5])

In [119]:
t1

tensor([[[[0.4793, 0.2979, 0.9938, 0.2382, 0.2526]],

         [[0.5390, 0.7074, 0.0903, 0.5773, 0.7162]],

         [[0.0708, 0.0152, 0.8679, 0.5135, 0.6637]]]])

In [120]:
t2 = t1.squeeze()

In [121]:
t2.shape

torch.Size([3, 5])

In [122]:
x = torch.rand(shape)

In [123]:
x.shape

torch.Size([1, 3, 1, 5])

In [124]:
x.squeeze(0).shape

torch.Size([3, 1, 5])

In [127]:
x.squeeze(1).shape ## will not change because the first dimension is not 1

torch.Size([1, 3, 1, 5])

## Tensor - unsqueeze() - opposite of squueze, will add a dimension of 1 at a specific index

In [130]:
x.shape

torch.Size([1, 3, 1, 5])

In [132]:
x.unsqueeze(0).shape

torch.Size([1, 1, 3, 1, 5])

In [135]:
x.unsqueeze(4).shape

torch.Size([1, 3, 1, 5, 1])

## Quick check

In [144]:
A = torch.arange(1,13).view([3,4])

In [141]:
type(A)


torch.Tensor

In [145]:
A

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [146]:
A.shape

torch.Size([3, 4])

In [147]:
A.T

tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])

In [148]:
A = A.T

In [149]:
A

tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])

In [150]:
A.shape

torch.Size([4, 3])

In [151]:
A1 = torch.rand(2,3)

In [152]:
A2 = torch.rand(3,2)

In [154]:
A1.shape

torch.Size([2, 3])

In [155]:
A2.shape

torch.Size([3, 2])

In [157]:
A1.matmul(A2)

tensor([[0.7727, 0.2291],
        [0.5926, 0.6132]])

In [158]:
C = torch.rand(5,5)

In [159]:
C

tensor([[0.9843, 0.9434, 0.3582, 0.0161, 0.8367],
        [0.4868, 0.8154, 0.6453, 0.8197, 0.1257],
        [0.3792, 0.7888, 0.2287, 0.4742, 0.4087],
        [0.0345, 0.9699, 0.0754, 0.0467, 0.6085],
        [0.5995, 0.2169, 0.0701, 0.9633, 0.5655]])

In [160]:
C[0]

tensor([0.9843, 0.9434, 0.3582, 0.0161, 0.8367])

In [161]:
C[:,-1]

tensor([0.8367, 0.1257, 0.4087, 0.6085, 0.5655])

In [163]:
C[1:4,1:4]

tensor([[0.8154, 0.6453, 0.8197],
        [0.7888, 0.2287, 0.4742],
        [0.9699, 0.0754, 0.0467]])